#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton &
# conky &
nitrogen --restore &
polybar &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
normal_border_color #585b70
active_border_color #585b70
focused_border_color #a6e3a1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -option grp:alt_shift_toggle us,ar &
